# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'sample3' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PageMenu'

  # Pods for sample3

  target 'sample3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sample3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
